apiVersion: kubeadm.k8s.io/v1beta2
clusterName: rnd-k8s-2020-a-eu-west-02
kind: ClusterConfiguration
api:
    controlPlaneEndpoint: "https://ip-10-0-34-130.eu-west-2.compute.internal:6443"
    advertisedAddress: 10.0.34.130
etcd:
  local:
    extraArgs:
      name: "ip-10-0-34-130.eu-west-2.compute.internal=10.0.34.130"
      listen-client-urls: "https://127.0.0.1:2379,https://10.0.34.130:2379"
      advertise-client-urls: "https://10.0.34.130:2379,https://127.0.0.1:2379"
      listen-peer-urls: "https://10.0.34.130:2380,https://127.0.0.1:2380"
      initial-advertise-peer-urls: "https://10.0.34.130:2380,https://127.0.0.1:2380"
      initial-cluster: "ip-10-0-34-130.eu-west-2.compute.internal=https://10.0.34.130:2380"
      initial-cluster-state: existing
    serverCertSANs:
      - ip-10-0-34-130.eu-west-2.compute.internal
      - 10.0.34.130
    peerCertSANs:
      - ip-10-0-34-130.eu-west-2.compute.internal
      - 10.0.34.130
    endpoints:
      - https://10.0.34.130:2379
    caFile: /etc/kubernetes/pki/etcd/ca.pem
    certFile: /etc/kubernetes/pki/etcd/client.pem
    keyFile: /etc/kubernetes/pki/etcd/client-key.pem

networking:
    podSubnet: "192.168.0.0/16"
kubernetesVersion: "v1.17.0"
apiServerExtraArgs:
  cloud-provider: aws
controllerManagerExtraArgs:
  cloud-provider: aws
apiServerCertSANs:
- "ip-10-0-34-130.eu-west-2.compute.internal"
controlPlaneEndpoint: "ip-10-0-34-130.eu-west-2.compute.internal:6443"
nodeRegistration:
  name: "ip-10-0-34-130.eu-west-2.compute.internal"
  kubeletExtraArgs:
    cloud-provider: aws

kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cgroup-driver: "systemd"
